### ISSUE TITLE
./es/index.js does not exist

### ISSUE THREAD

**Issue by FDiskas** [maxzinchenko/redux-awesome-socket-middleware#1]
https://github.com/maxzinchenko/redux-awesome-socket-middleware/blob/0656fa5abc64f5a625c7fbf444d9d66b386c55e3/package.json#L28

The list of available files: https://unpkg.com/browse/redux-awesome-socket-middleware@1.1.5/

**Comment by maxzinchenko** [comment]
Thanks for the issue.
Will fix it shortly!

**Comment by maxzinchenko** [comment]
Closing the issue.
[PR](https://github.com/maxzinchenko/redux-awesome-socket-middleware/pull/3/) of the issue.
