### ISSUE TITLE
set headers

### ISSUE THREAD

**Issue by watt-niu** [maxzinchenko/redux-awesome-socket-middleware#11]
I want to set the request header, such as Authorization or something, and my url is variable, when I arrive at a page, I will connect to ws, the url is like ws://xxx.xxx.com/abc/{code}, I don't know how to do, can you help to deal with similar scenarios

**Comment by maxzinchenko** [comment]
Hello, @niujianqiang123 !
Ideally, it should be 2 sockets. 

The first one is for authorization API (through cookies)
The second one is for the authorized API (should be connected with the auth service and verify the auth from cookies).

So, basically, you need to create 2 sockets with different options and different slices in redux.

**Comment by maxzinchenko** [comment]
The lib uses the WebSocket from the Browser API.

The WebSocket client API doesn't allow sending custom headers, they allow you to set exactly one header, namely Sec-WebSocket-Protocol, i.e. the application-specific subprotocol.

**Comment by maxzinchenko** [comment]
Closed the issue: no answer from the reporter.
