### ISSUE TITLE
Uncaught DOMException: Failed to construct 'WebSocket': The URL 'undefined' is invalid.

### ISSUE THREAD

**Issue by FDiskas** [maxzinchenko/redux-awesome-socket-middleware#2]
https://github.com/maxzinchenko/redux-awesome-socket-middleware/blob/d766939637b812ff517dcc14ca5c670e567977b9/src/services/WebSocket/index.ts#L52

![image](https://user-images.githubusercontent.com/468006/151843931-89d43393-8f87-4f81-a819-c24a6cbe2ad5.png)

**Comment by maxzinchenko** [comment]
hello, @FDiskas!

The `url` is a required `WebSocket` constructor's parameter that cannot be `undefined`.
You need to create a middleware using the `createSocketMiddleware` function and pass the `url` to there.
